### ISSUE TITLE
Wildcard selector for insights_export

### ISSUE THREAD

**Issue by serra92** [mariusandra/insights#8]
Hey. Nice job with insights!

I've been fiddling around with insights and I am trying to export my Active Record to the insights.yml file, but i only want to include some models. It would be nice to have a feature like a wildcard or specific taks to select specific Models to be exported.

Thanks and keep up the good work

**Comment by mariusandra** [comment]
Hey, I released version 0.2.0 of `insights_export` which lets you filter the models you export. Check it out here: https://github.com/mariusandra/insights_export

Will this be enough?

Also, since the export script tries to be nice and not delete any data from the `insights.yml` file, if you have already exported all the models, you will need to either delete the file and re-export everything, or delete the relevant parts manually.
